UPDATE shows SET title = 'Adventure Time' WHERE LOWER(TRIM(title)) = 'adventure time';
UPDATE shows SET title = 'Arrow' WHERE LOWER(TRIM(title)) = 'arrow';
UPDATE shows SET title = 'Avatar: The Last Airbender' WHERE LOWER(TRIM(title)) IN ('avatar the last airbender', 'avatar');
UPDATE shows SET title = 'Billions' WHERE LOWER(TRIM(title)) = 'billions';
UPDATE shows SET title = 'Brooklyn Nine-Nine' WHERE LOWER(TRIM(title)) IN ('brooklyn-99', 'b99', 'brooklyn 99');
UPDATE shows SET title = 'Community' WHERE LOWER(TRIM(title)) = 'community';
UPDATE shows SET title = 'Criminal Minds' WHERE LOWER(TRIM(title)) = 'criminal minds';
UPDATE shows SET title = 'Family Guy' WHERE LOWER(TRIM(title)) = 'family guy';
UPDATE shows SET title = 'Friends' WHERE LOWER(TRIM(title)) = 'friends';
UPDATE shows SET title = 'Game of Thrones' WHERE LOWER(TRIM(title)) = 'got';
UPDATE shows SET title = 'Gilmore Girls' WHERE LOWER(TRIM(title)) = 'gilmore girls';
UPDATE shows SET title = 'Grey's Anatomy' WHERE LOWER(TRIM(title)) = 'grey's anatomy';
UPDATE shows SET title = 'How I Met Your Mother' WHERE LOWER(TRIM(title)) = 'how i met your mother';
UPDATE shows SET title = 'It's Always Sunny in Philadelphia' WHERE LOWER(TRIM(title)) = 'its always sunny in philidelphia';
UPDATE shows SET title = 'Law and Order' WHERE LOWER(TRIM(title)) = 'law and order';
UPDATE shows SET title = 'Parks and Recreation' WHERE LOWER(TRIM(title)) = 'parks and rec';
UPDATE shows SET title = 'Sherlock' WHERE LOWER(TRIM(title)) = 'sherlock holmes';
UPDATE shows SET title = 'Squid Game' WHERE LOWER(TRIM(title)) = 'squid game';
UPDATE shows SET title = 'The Bachelorette' WHERE LOWER(TRIM(title)) = 'the bachelorette';
UPDATE shows SET title = 'The Crown' WHERE LOWER(TRIM(title)) = 'the crown';
UPDATE shows SET title = 'The Office' WHERE LOWER(TRIM(title)) IN ('office', 'the office', 'thevoffice');
UPDATE shows SET title = 'The Queen's Gambit' WHERE LOWER(TRIM(title)) = 'queen’s gambit';
UPDATE shows SET title = 'The Untamed' WHERE LOWER(TRIM(title)) = 'the untamed';
